services:
  - type: web
    name: ticketingapp
    env: python
    plan: starter
    buildCommand: 
      - pip install --no-cache-dir -r requirements.txt
      - python manage.py collectstatic --noinput
    startCommand: gunicorn ticketingSystem.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DJANGO_DEBUG
        value: 'False'
      - key: DJANGO_ALLOWED_HOSTS
        value: '*'
