services:
  - type: web
    name: django-app
    env: docker
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: ""
    dockerfilePath: Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ticketingSystem.settings
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: DEBUG
        value: "0"
