# Generated by Django 5.0.4 on 2024-04-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tickets",
            "0003_rename_is_assigned_to_rngineer_ticket_is_assigned_to_engineer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Pending", "Pending"),
                    ("Resolved", "Resolved"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
